FROM opentracing/nginx-opentracing:edge

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/vhost.conf /etc/nginx/conf.d/vhost.conf
COPY certs /certs
COPY nginx/jaeger-nginx-config.json /etc/jaeger-nginx-config.json
