# TESTING PURPOSES ONLY
# for more details check `config.yml`
################################################################################
server:
  port:
    http: "8080"
    https: "8443"
  tls:
    cert_file: server.pem
    key_file: server.key
  timeout:
    read: 5s
    read_header: 2s
    write: 5s
    idle: 20s
    handler: 15s

domains:
  example_com:
    server:
      upstream:
        host: example.com

  example_org:
    server:
      upstream:
        host: example.org

  www_w3_org:
    server:
      upstream:
        host: www.w3.org
        endpoints:
        - www.w3.org

  www_fabiocicerchia_it:
    server:
      upstream:
        host: www.fabiocicerchia.it
        endpoints:
        - www.fabiocicerchia.it

  fabiocicerchia_it:
    server:
      upstream:
        host: fabiocicerchia.it
        endpoints:
        - 161.35.67.75:443
