FROM fabiocicerchia/nginx-lua:1.21.6-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ="Europe/London"

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
      python3 python3-pip

RUN pip3 install grpcio

# Ref: https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx#usage
# Ref: https://github.com/open-telemetry/opentelemetry-cpp-contrib/actions/runs/2043949860
COPY --chown=nginx:nginx nginx/otel_ngx_module.so /etc/nginx/otel_ngx_module.so
COPY --chown=nginx:nginx nginx/nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx nginx/conf.d/vhost.conf /etc/nginx/conf.d/vhost.conf
COPY --chown=nginx:nginx certs /certs
COPY --chown=nginx:nginx nginx/otel-nginx.toml /conf/otel-nginx.toml
COPY --chown=nginx:nginx nginx/.htpasswd /etc/nginx/.htpasswd
