FROM docker:dind

ENV DEBIAN_FRONTEND=noninteractive
ENV REPO_URL=https://raw.githubusercontent.com/getsentry/self-hosted/master/install
ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1

RUN apk update \
    && apk add \
      curl \
      git \
      bash \
      ca-certificates \
      curl \
      gnupg

RUN apk update \
    && apk add \
      docker

RUN apk add py-pip \
    && apk add python3-dev libffi-dev openssl-dev gcc libc-dev make \
    && pip install docker-compose

RUN git clone https://github.com/getsentry/self-hosted.git

WORKDIR /self-hosted

CMD ["./install.sh"]
