#                                                                         __
# .-----.-----.______.-----.----.-----.--.--.--.--.______.----.---.-.----|  |--.-----.
# |  _  |  _  |______|  _  |   _|  _  |_   _|  |  |______|  __|  _  |  __|     |  -__|
# |___  |_____|      |   __|__| |_____|__.__|___  |      |____|___._|____|__|__|_____|
# |_____|            |__|                   |_____|
#
# Copyright (c) 2022 Fabio Cicerchia. https://fabiocicerchia.it. MIT License
# Repo: https://github.com/fabiocicerchia/go-proxy-cache

FROM ubuntu:24.04 AS builder

ARG BUILD_CMD=build

WORKDIR /go/src/github.com/fabiocicerchia/go-proxy-cache

ENV CGO_CFLAGS -march=native -O3
ENV PATH=/usr/local/go/bin:$PATH

RUN apt update \
    && apt install -y \
      ca-certificates \
      gcc \
      make \
      wget

RUN wget https://go.dev/dl/go1.25.5.linux-$(dpkg --print-architecture).tar.gz \
    && tar -C /usr/local -xzf go1.25.5.linux-$(dpkg --print-architecture).tar.gz

COPY . ./

RUN make $BUILD_CMD

FROM ubuntu:24.04

WORKDIR /app

COPY --from=builder /go/src/github.com/fabiocicerchia/go-proxy-cache/go-proxy-cache /usr/local/bin/
COPY --from=builder /go/src/github.com/fabiocicerchia/go-proxy-cache/config.yml.dist /app/config.yml

RUN apt-get update \
    && apt-get upgrade -y \
    # libcap2-bin: grant the binary CAP_NET_BIND_SERVICE so it can still bind
    # the privileged 80/443 default ports as a non-root user below.
    && apt-get install -y --no-install-recommends libcap2-bin \
    && rm -rf /var/lib/apt/lists/* \
    && setcap 'cap_net_bind_service=+ep' /usr/local/bin/go-proxy-cache \
    && useradd -m -u 10001 gpc \
    && chown gpc:gpc /app/config.yml

RUN go-proxy-cache --version \
    && go-proxy-cache --test

USER gpc

CMD ["go-proxy-cache"]
