#                                                                         __
# .-----.-----.______.-----.----.-----.--.--.--.--.______.----.---.-.----|  |--.-----.
# |  _  |  _  |______|  _  |   _|  _  |_   _|  |  |______|  __|  _  |  __|     |  -__|
# |___  |_____|      |   __|__| |_____|__.__|___  |      |____|___._|____|__|__|_____|
# |_____|            |__|                   |_____|
#
# Copyright (c) 2023 Fabio Cicerchia. https://fabiocicerchia.it. MIT License
# Repo: https://github.com/fabiocicerchia/go-proxy-cache

FROM golang:1.25-alpine3.23 AS builder

ARG BUILD_CMD=build

WORKDIR /go/src/github.com/fabiocicerchia/go-proxy-cache

ENV CGO_CFLAGS -march=native -O3

RUN apk update \
    && apk add --no-cache \
      gcc \
      libc-dev \
      make

COPY . ./

RUN make $BUILD_CMD

FROM alpine:3.23.3

WORKDIR /app

COPY --from=builder /go/src/github.com/fabiocicerchia/go-proxy-cache/go-proxy-cache /usr/local/bin/
COPY --from=builder /go/src/github.com/fabiocicerchia/go-proxy-cache/config.yml.dist /app/config.yml

RUN apk upgrade \
    # libcap: grant the binary CAP_NET_BIND_SERVICE so it can still bind the
    # privileged 80/443 default ports as a non-root user below.
    && apk add --no-cache libcap \
    && setcap 'cap_net_bind_service=+ep' /usr/local/bin/go-proxy-cache \
    && adduser -D -u 10001 gpc \
    && chown gpc:gpc /app/config.yml

RUN go-proxy-cache --version \
    && go-proxy-cache --test

USER gpc

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD wget -q -O- http://127.0.0.1:52021/healthcheck || exit 1

CMD ["go-proxy-cache"]
