linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - interfacer
    - maligned
    - scopelint
    - wrapcheck

issues:
  exclude-rules:
    - text: could not import C (cgo preprocessing failed)
      linters: [typecheck]
