line-length: false
MD014: false # Dollar signs used before commands without showing output
MD024: false # Multiple headings with the same content
MD026: # Trailing punctuation in heading
  punctuation: ".,;:!。，；：！？"
MD029: false # Ordered list item prefix
MD033: # Inline HTML
  allowed_elements:
    - center
    - details
    - summary
MD038: false # Spaces inside code span elements
