---
apiVersion: v1
kind: Service
metadata:
  labels:
    meta.service: go-proxy-cache
  name: go-proxy-cache
spec:
  ports:
  - name: "50080"
    port: 50080
    targetPort: 50080
  - name: "50443"
    port: 50443
    targetPort: 50443
  selector:
    meta.service: go-proxy-cache
