{
 "title": "GPC Overall",
 "description": "Go Proxy Cache - Overall Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(env)" } },
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(hostname)" } },
   { "name": "server", "label": "Server", "query": { "query": "label_values(server)" } },
   { "name": "upstream", "label": "Upstream", "query": { "query": "label_values(upstream)" } }
  ]
 },
 "panels": [
  {
   "title": "Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "gpcee_http_requests_total{env=\"$environment\", hostname=~\"$hostname\"}",
       "legendFormat": "{{hostname}}"
      },
      {
       "expr": "sum(gpcee_http_requests_total{env=\"$environment\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Host Health Ratio",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gpc_host_healthy{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Healthy"
      },
      {
       "expr": "sum(gpc_host_unhealthy{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Unhealthy"
      }
     ]
    },
    {
     "title": "Cache Ratio",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(gpc_cache_hits_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Hit"
      },
      {
       "expr": "avg(gpc_cache_miss_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Miss"
      },
      {
       "expr": "avg(gpc_cache_stale_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Stale"
      }
     ]
    },
    {
     "title": "Status Code Ratio",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (code) (gpc_status_codes_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "HTTP Methods Ratio",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (method) (gpc_http_methods_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "URL Scheme Ratio",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (scheme) (gpc_url_scheme_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "{{scheme}}"
      }
     ]
    },
    {
     "title": "Requested Hosts",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (host) (gpc_request_host_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Hit vs Miss vs Stale",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg(gpc_cache_hits_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Hit"
      },
      {
       "expr": "avg(gpc_cache_miss_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Miss"
      },
      {
       "expr": "avg(gpc_cache_stale_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Stale"
      }
     ]
    },
    {
     "title": "Healthy vs Unhealthy Hosts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "sum(gpc_host_healthy{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "Healthy"
      },
      { "expr": "sum(gpc_host_unhealthy)", "legendFormat": "Unhealthy" }
     ]
    },
    {
     "title": "Requests by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "sum by (code) (gpc_status_codes_total{env=\"$environment\", hostname=~\"$hostname\"})",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "avg by (env,server,upstream) (gpcee_upstream_server_health_checks_status{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"})"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "description": "Total ms time to get the full response from the server.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "gpcee_upstream_server_response_time{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"}",
       "legendFormat": "{{server}}/{{upstream}}"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "timeseries",
     "description": "Total client requests.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "gpcee_upstream_server_requests{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"}",
       "legendFormat": "{{server}}/{{upstream}}"
      }
     ]
    },
    {
     "title": "Total Responses",
     "type": "timeseries",
     "description": "Total responses sent to clients.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "gpcee_upstream_server_responses{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"}",
       "legendFormat": "{{server}}/{{upstream}} - {{code}}"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "timeseries",
     "description": "Bytes sent from this server.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "gpcee_upstream_server_sent{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"}",
       "legendFormat": "{{server}}/{{upstream}}"
      }
     ]
    },
    {
     "title": "Bytes Received",
     "type": "timeseries",
     "description": "Bytes received to this server.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "gpcee_upstream_server_received{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"}",
       "legendFormat": "{{server}}/{{upstream}}"
      }
     ]
    },
    {
     "title": "Health Checks",
     "type": "timeseries",
     "description": "Total health check requests.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "gpcee_upstream_server_health_checks_checks{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"}-gpcee_upstream_server_health_checks_checks{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"} offset $__interval > 0\n",
       "legendFormat": "{{server}}/{{upstream}}"
      }
     ]
    },
    {
     "title": "Health Checks Failures",
     "type": "timeseries",
     "description": "Failed health checks.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "gpcee_upstream_server_health_checks_fails{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"}-gpcee_upstream_server_health_checks_fails{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"} offset $__interval > 0\n",
       "legendFormat": "{{server}}/{{upstream}}"
      }
     ]
    },
    {
     "title": "Unhealthy Upstreams",
     "type": "timeseries",
     "description": "How many times the server became unhealthy (state 'unhealthy').",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "gpcee_upstream_server_health_checks_unhealthy{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"}-gpcee_upstream_server_health_checks_unhealthy{env=\"$environment\", hostname=~\"$hostname\", server=~\"$server\", upstream=~\"$upstream\"} offset $__interval > 0",
       "legendFormat": "{{server}}/{{upstream}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Build",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPC Build",
     "type": "table",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "gpcee_generic_build_info{env=\"$environment\", hostname=~\"$hostname\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Routines",
     "type": "timeseries",
     "description": "Number of goroutines that currently exist.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "go_goroutines{job=\"go-proxy-cache\"}",
       "legendFormat": "go-proxy-cache"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "timeseries",
     "description": "Number of bytes allocated and still in use.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"go-proxy-cache\"}",
       "legendFormat": "go-proxy-cache"
      }
     ]
    },
    {
     "title": "Go Threads",
     "type": "timeseries",
     "description": "Number of OS threads created.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "go_threads{job=\"go-proxy-cache\"}",
       "legendFormat": "go-proxy-cache"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "description": "Maximum number of open file descriptors.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_max_fds{job=\"go-proxy-cache\"}",
       "legendFormat": "Max FDs allowed"
      },
      {
       "expr": "process_open_fds{job=\"go-proxy-cache\"}",
       "legendFormat": "Current FDs"
      }
     ]
    },
    {
     "title": "CPU Time",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"go-proxy-cache\"}[1m])",
       "legendFormat": "go-proxy-cache"
      }
     ]
    }
   ]
  }
 ]
}