on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: git fetch --prune --unshallow --tags

      - name: Create changelogs
        id: changelogs
        uses: heineiuo/create-changelogs@master

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelogs.outputs.changelogs }}
          draft: false
          prerelease: ${{ steps.changelogs.outputs.release_type == 'prerelease' }}

      - uses: ethomson/send-tweet-action@v1
        with:
          status: "The version ${{ github.ref }} of go-proxy-cache has been released. https://github.com/fabiocicerchia/go-proxy-cache"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
